apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-azure-servicemonitor
  namespace: monitoring
  labels:
    prometheus: main    # ✅ Must match serviceMonitorSelector in Prometheus
spec:
  selector:
    matchLabels:
      app: spring-azure-app    # ✅ Must match Service labels
  namespaceSelector:
    matchNames:
    - springboot-app           # ✅ Your app namespace
  endpoints:
  - port: http                 # ✅ Port name in Service
    interval: 15s
    path: /actuator/prometheus # ✅ Spring Boot Prometheus endpoint

