apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-azure-app
  namespace: springboot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-azure-app
  template:
    metadata:
      labels:
        app: spring-azure-app
    spec:
      serviceAccountName: springboot-service-account
      containers:
      - name: spring-azure-app
        image: ireachaksacr.azurecr.io/spring-azure-app:latest
        ports:
        - containerPort: 8080

