

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-azure-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: app.ireachdevops.net  # Replace with your actual domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spring-azure-service
            port:
              number: 80
