

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-azure-ingress
  # annotations can be added here if needed
spec:
  ingressClassName: nginx   # <-- Move this here (not under annotations)
  rules:
  - host: app.ireachdevops.net  # Replace with your actual domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spring-azure-service
            port:
              number: 80

