apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-azure-servicemonitor
  namespace: monitoring          # must be where Prometheus operator runs
  labels:
    release: prometheus-operator  # ensure this matches Prometheus's serviceMonitorSelector
spec:
  selector:
    matchLabels:
      app: spring-azure-app      # matches your service label in springboot-app namespace
  namespaceSelector:
    matchNames:
    - springboot-app             # namespace where your app and service live
  endpoints:
  - port: http                   # port name in your Service YAML
    interval: 15s
    path: /actuator/prometheus
