name: Build and Deploy to AKS

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

env:
  ACR_NAME: ireachaksacr
  RESOURCE_GROUP: ireach-aks-resource-group
  AKS_CLUSTER: ireach-aks-cluster
  DEPLOYMENT_NAME: myspringbootapp
  NAMESPACE: springboot-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full history is available for Gitleaks

      - name: Run Gitleaks to detect secrets
        id: gitleaks
        uses: DariuszPorowski/github-action-gitleaks@v2
        with:
          fail: false
          report_format: json
          redact: true
          verbose: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Login to Azure CLI using OIDC
        uses: azure/login@v1
        with:
          client-id: 49362974-4ee2-4f88-b5cf-5d90b8d7e5e9
          tenant-id: 99c759c0-ce79-4f6e-839d-1895a7e65c69
          subscription-id: 76f766cd-6240-4268-8e8c-800713bfa372

      - name: Docker login to ACR
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/spring-azure-app:${{ github.sha }} .

      - name: Push Docker image to ACR
        run: |
          docker push ${{ env.ACR_NAME }}.azurecr.io/spring-azure-app:${{ github.sha }}

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan Docker image with Trivy for vulnerabilities
        run: |
          trivy image --severity CRITICAL,HIGH --ignore-unfixed ${{ env.ACR_NAME }}.azurecr.io/spring-azure-app:${{ github.sha }}

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER }}

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} springboot-app=${{ env.ACR_NAME }}.azurecr.io/spring-azure-app:${{ github.sha }} -n ${{ env.NAMESPACE }}
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ env.NAMESPACE }}
